# Generated by Django 3.0.8 on 2020-09-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chit', models.TextField(verbose_name='chit')),
                ('status', models.IntegerField(choices=[(0, 'Disapproved'), (1, 'Checking'), (2, 'Approved'), (3, 'Ratified')])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('chit_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chits', to='accounts.Country')),
                ('chit_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_chits', to='accounts.Country')),
                ('reply_to_chit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='chits.Chit')),
            ],
            options={
                'verbose_name': 'chit',
                'verbose_name_plural': 'chits',
                'ordering': ['timestamp'],
                'get_latest_by': '-timestamp',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('chits', models.ManyToManyField(related_name='round_in', to='chits.Chit')),
                ('teams', models.ManyToManyField(related_name='round', to='accounts.Team')),
            ],
        ),
    ]
